# Source-make
FILENAME=irc
include ../Makefile.generic
irc.o: \
   ../module.h \
   irc.h \
   ../server.mod/server.h \
   ../channels.mod/channels.h \
   chan.c \
   mode.c \
   cmdsirc.c \
   msgcmds.c \
   tclirc.c
