#! /bin/sh
# $Id: buildstatic,v 1.3 1999/12/21 17:35:10 fabian Exp $

rm -f static.h
for i in *.mod
do
y=`echo $i | sed s/.mod//`
cat >> static.h << EOF
char *${y}_start();
EOF
done
cat >> static.h << EOF
static void link_statics() {
EOF
for i in *.mod
do
y=`echo $i | sed s/.mod//`
cat >> static.h << EOF
  check_static("${y}", ${y}_start);
EOF
done
cat >> static.h << EOF
}
EOF
