#! /bin/sh

rm -f static.h
for i in *.mod
do
y=`echo $i | sed s/.mod//`
cat >> static.h << EOF
char * ${y}_start();
EOF
done
cat >> static.h << EOF
static void link_statics() {
EOF
for i in *.mod
do
y=`echo $i | sed s/.mod//`
cat >> static.h << EOF
check_static("${y}",${y}_start);
EOF
done
cat >> static.h << EOF
}
EOF
