name: Autotools check

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]

jobs:
  default-build:
    name: Check if autotools need to be run
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt-get install build-essential autoconf
    - name: Stage configure with revision removed
      run: |
        for i in `find . -name configure`; do sed -i 's/From configure.ac .*//' $i; git add $i; done
    - name: Run autotools
      run: misc/runautotools
    - name: Remove configure revision again
      run: |
        for i in `find . -name configure`; do sed -i 's/From configure.ac .*//' $i; done
    - name: Check diff
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        git diff | tee .gitdiff
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          if [ -s .gitdiff ]; then
            gh pr edit "${{ github.event.number }}" --add-label "misc/runautotools"
          else
            gh pr edit "${{ github.event.number }}" --remove-label "misc/runautotools"
          fi
        else
          if [ -s .gitdiff ]; then
            exit 1
          fi
        fi
