name: Eggdrop Compile

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]

jobs:
  default-build:
    name: Compile Test
    strategy:
      matrix:
        cc: [ 'gcc', 'clang' ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt-get install clang tcl tcl-dev openssl libssl-dev
    - name: Build
      env:
        CC: ${{ matrix.cc }}
      run: ./configure && make config && make -j4 && make install
  feature-test:
    name: Features
    continue-on-error: true
    strategy:
      matrix:
        conf_tls: [ '', '--disable-tls' ]
        conf_ipv6: [ '', '--disable-ipv6' ]
        conf_tdns: [ '', '--disable-tdns' ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt-get install tcl tcl-dev openssl libssl-dev
    - name: Build
      run: ./configure ${{ matrix.conf_tls }} ${{ matrix.conf_ipv6 }} ${{ matrix.conf_tdns }} && make config && make -j4
  tcl-versions:
    name: Tcl Versions
    strategy:
      matrix:
        tcl_version: [ '8.5.19', '8.6.14', '8.7a5', '9.0b2' ]
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt-get install openssl libssl-dev
    - name: Build Tcl
      run: |
        wget http://prdownloads.sourceforge.net/tcl/tcl${{ matrix.tcl_version }}-src.tar.gz && \
        tar xzf tcl${{ matrix.tcl_version }}-src.tar.gz && \
        cd tcl${{ matrix.tcl_version }}/unix && \
        ./configure --prefix=$HOME/tcl && \
        make -j4 && make install
    - name: Build
      run: ./configure --with-tcl=$HOME/tcl/lib && LD_LIBRARY_PATH=$HOME/tcl/lib make config eggdrop
  ssl-versions-3x:
    name: OpenSSL 3.x
    strategy:
      matrix:
        ssl_version: [ '3.0', '3.1', '3.2', '3.3' ]
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
    - uses: oprypin/find-latest-tag@v1
      with:
        repository: openssl/openssl
        releases-only: true
        prefix: 'openssl-'
        regex: "${{ matrix.ssl_version }}.[0-9]+"
        sort-tags: true
      id: openssl
    - uses: actions/checkout@v4
      with:
        repository: openssl/openssl
        ref: ${{ steps.openssl.outputs.tag }}
        path: 'openssl'
    - name: Build OpenSSL
      run: |
        cd $GITHUB_WORKSPACE/openssl && ./config --prefix=$HOME/ssl && make -j4 && make install_sw
    - uses: actions/checkout@v4
      with:
        path: 'eggdrop'
    - name: install dependencies
      run: sudo apt-get install tcl tcl-dev
    - name: Build
      run: cd $GITHUB_WORKSPACE/eggdrop && ./configure --with-sslinc=$HOME/ssl/include --with-ssllib=$HOME/ssl/lib64 && LD_LIBRARY_PATH=$HOME/ssl/lib64 make config eggdrop
  ssl-version-11:
    name: OpenSSL 1.1
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: openssl/openssl
        ref: 'OpenSSL_1_1_1w'
        path: 'openssl'
    - name: Build OpenSSL
      run: |
        cd $GITHUB_WORKSPACE/openssl && ./config --prefix=$HOME/ssl && make -j4 && make install_sw
    - name: install dependencies
      run: sudo apt-get install tcl tcl-dev
    - uses: actions/checkout@v4
      with:
        path: 'eggdrop'
    - name: Build
      run: cd $GITHUB_WORKSPACE/eggdrop && ./configure --with-sslinc=$HOME/ssl/include --with-ssllib=$HOME/ssl/lib && LD_LIBRARY_PATH=$HOME/ssl/lib make config eggdrop
  ssl-version-10:
    name: OpenSSL 1.0
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with: 
        path: 'eggdrop'
    - name: install dependencies
      run: sudo apt-get install tcl tcl-dev
    - name: Build OpenSSL
      run: |
        wget https://www.openssl.org/source/old/1.0.2/openssl-1.0.2u.tar.gz && tar xzf openssl-1.0.2u.tar.gz && \
        cd openssl-1.0.2u && ./config --prefix=$HOME/ssl -fPIC && make -j4 && make install_sw
    - name: Build
      run: cd $GITHUB_WORKSPACE/eggdrop && ./configure --with-sslinc=$HOME/ssl/include --with-ssllib=$HOME/ssl/lib && LD_LIBRARY_PATH=$HOME/ssl/lib make config eggdrop
