name: Check autotools/makedepend

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]

jobs:
  autotools-check:
    name: Check if misc/runautotools needs to be run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt-get update && sudo apt-get install build-essential autoconf
    - name: Stage configure with revision removed
      run: |
        for i in `find . -name configure`; do sed -i 's/From configure.ac .*//' $i; git add $i; done
    - name: Run autotools
      run: misc/runautotools
    - name: Remove configure revision again
      run: |
        for i in `find . -name configure`; do sed -i 's/From configure.ac .*//' $i; done
    - name: Check diff
      run: |
        git diff | tee .gitdiff
        if [ -s .gitdiff ]; then
          exit 1
        fi
  makedepend-check:
    name: Check if misc/makedepend needs to be run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt-get update && sudo apt-get install build-essential autoconf tcl-dev tcl openssl libssl-dev
    - name: Run makedepend
      run: misc/makedepend
    - name: Check diff
      run: |
        git diff | tee .gitdiff
        if [ -s .gitdiff ]; then
          exit 1
        fi
